name: main

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: cache word list
        uses: actions/cache@v2
        with:
          path: node_modules/wordList-cache.txt
          key: wordList-cache
          restore-keys: wordList-cache

      - run: pnpm type

      - run: pnpm lint

      - run: pnpm test

      - run: pnpm build

      - run: npm pack
        working-directory: dist

      - name: npm publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm publish dist/*.tgz
        # if: success() && github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
