name: test

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm type

      - run: pnpm lint

      - run: pnpm start
