name: test

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm type

      - run: pnpm lint

      - run: pnpm test

      - name: cache word list
        uses: actions/cache@v2
        with:
          path: node_modules/wordList-cache.txt
          key: wordList-cache
          restore-keys: wordList-cache

      - run: pnpm start
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
