name: solve-daily

on:
  # run automatically every day at 9:00 AM
  # schedule:
  #   - cron: "0 9 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  solve-daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: cache word list
        uses: actions/cache@v2
        with:
          path: node_modules/wordList-cache.txt
          key: wordList-cache
          restore-keys: wordList-cache

      - run: pnpm twitter-refresh
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_REFRESH_TOKEN: ${{ secrets.TWITTER_REFRESH_TOKEN }}

      - run: pnpm start
        timeout-minutes: 2
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          # the fresh access token is read from the .env file created by the previous step
